version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.4-jdk-8-alpine
    steps:
      - checkout
      - run:
          name: Stats tests
          command: mvn test || exit 0 # Always exit with success code.
          working_directory: stats-tests
